Turn on CI

diff --git a/.github/workflows/macos-system-ci.yml b/.github/workflows/macos-system-ci.yml
--- a/.github/workflows/macos-system-ci.yml
+++ b/.github/workflows/macos-system-ci.yml
@@ -1,145 +1,145 @@
-# # Runs the installation tests in the following cases:
-# #   1) every day at 3 am
-# #   2) a pull request to the master branch
+# Runs the installation tests in the following cases:
+#   1) every day at 3 am
+#   2) a pull request to the master branch
 
-# name: macOS System CI
+name: macOS System CI
 
-# on:
-#   schedule:
-#     # Every day at 3 am
-#     - cron: '0 3 * * *'
-#   pull_request:
-#     # Upon pull requests
-#     branches:
-#       - master
+on:
+  schedule:
+    # Every day at 3 am
+    - cron: '0 3 * * *'
+  pull_request:
+    # Upon pull requests
+    branches:
+      - master
 
-# jobs:
-#   build:
-#     strategy:
-#       matrix:
-#         os: [macos-11, macos-12]
+jobs:
+  build:
+    strategy:
+      matrix:
+        os: [macos-11, macos-12]
 
-#     runs-on: ${{ matrix.os }}
+    runs-on: ${{ matrix.os }}
 
-#     steps:
-#     - name: Make sure Xcode 14.1 is used on macOS 12 as the default /Application/Xcode.app
-#       shell: zsh {0}
-#       run: |
-#         sudo mv /Applications/Xcode.app /Applications/Xcode.app-
-#         sudo ln -s /Applications/Xcode_14.1.app /Applications/Xcode.app
-#         sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
-#       if: matrix.os == 'macos-12'
+    steps:
+    - name: Make sure Xcode 14.1 is used on macOS 12 as the default /Application/Xcode.app
+      shell: zsh {0}
+      run: |
+        sudo mv /Applications/Xcode.app /Applications/Xcode.app-
+        sudo ln -s /Applications/Xcode_14.1.app /Applications/Xcode.app
+        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
+      if: matrix.os == 'macos-12'
 
-#     - name: Make sure Xcode 13.1 is used on macOS 11 as the default /Application/Xcode.app
-#       shell: bash
-#       run: |
-#         sudo mv /Applications/Xcode.app /Applications/Xcode.app-
-#         sudo ln -s /Applications/Xcode_13.1.app /Applications/Xcode.app
-#         sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
-#       if: matrix.os == 'macos-11'
+    - name: Make sure Xcode 13.1 is used on macOS 11 as the default /Application/Xcode.app
+      shell: bash
+      run: |
+        sudo mv /Applications/Xcode.app /Applications/Xcode.app-
+        sudo ln -s /Applications/Xcode_13.1.app /Applications/Xcode.app
+        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
+      if: matrix.os == 'macos-11'
 
-#     - name: Set GHA_BRANCH_NAME
-#       run: |
-#         if [ "${{ github.event_name }}" = "push" ]; then
-#           echo "GHA_BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
-#         fi
-#         if [ "${{ github.event_name }}" = "pull_request" ]; then
-#           echo "GHA_BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
-#         fi
-#         if [ "${{ github.event_name }}" = "schedule" ]; then
-#           echo "GHA_BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
-#         fi
+    - name: Set GHA_BRANCH_NAME
+      run: |
+        if [ "${{ github.event_name }}" = "push" ]; then
+          echo "GHA_BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
+        fi
+        if [ "${{ github.event_name }}" = "pull_request" ]; then
+          echo "GHA_BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
+        fi
+        if [ "${{ github.event_name }}" = "schedule" ]; then
+          echo "GHA_BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
+        fi
     
-#     - name: Install BioDynaMo
-#       shell: zsh {0}
-#       run: |
-#         brew install curl
-#         curl https://raw.githubusercontent.com/BioDynaMo/biodynamo/${GHA_BRANCH_NAME}/util/install | bash
-#         # remove whole bidynamo repository to catch errors related to paths pointing into the build dir
-#         mktemp -d
-#         find /tmp -iname biodynamo -type d || true
-#         rm -rf $(find $(mktemp -d)/../* -maxdepth 1 -iname biodynamo -type d 2>/dev/null)
-#         echo "Removed"
-#         find /tmp -iname biodynamo -type d || true
+    - name: Install BioDynaMo
+      shell: zsh {0}
+      run: |
+        brew install curl
+        curl https://raw.githubusercontent.com/BioDynaMo/biodynamo/${GHA_BRANCH_NAME}/util/install | bash
+        # remove whole bidynamo repository to catch errors related to paths pointing into the build dir
+        mktemp -d
+        find /tmp -iname biodynamo -type d || true
+        rm -rf $(find $(mktemp -d)/../* -maxdepth 1 -iname biodynamo -type d 2>/dev/null)
+        echo "Removed"
+        find /tmp -iname biodynamo -type d || true
 
-#     - name: Checkout BioDynaMo
-#       uses: actions/checkout@v2
-#       with:
-#         fetch-depth: 0
+    - name: Checkout BioDynaMo
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
 
-#     - name: Set INSTALL_DIR
-#       run: |
-#         if [ "${{ github.event_name }}" = "push" ]; then
-#           echo "INSTALL_DIR=${GITHUB_WORKSPACE}/build" >> $GITHUB_ENV
-#         fi
-#         if [ "${{ github.event_name }}" = "pull_request" ]; then
-#           echo "INSTALL_DIR=${GITHUB_WORKSPACE}/build" >> $GITHUB_ENV
-#         fi
-#         if [ "${{ github.event_name }}" = "schedule" ]; then
-#           echo "INSTALL_DIR=$(echo ${HOME}/biodynamo-*)" >> $GITHUB_ENV
-#         fi
+    - name: Set INSTALL_DIR
+      run: |
+        if [ "${{ github.event_name }}" = "push" ]; then
+          echo "INSTALL_DIR=${GITHUB_WORKSPACE}/build" >> $GITHUB_ENV
+        fi
+        if [ "${{ github.event_name }}" = "pull_request" ]; then
+          echo "INSTALL_DIR=${GITHUB_WORKSPACE}/build" >> $GITHUB_ENV
+        fi
+        if [ "${{ github.event_name }}" = "schedule" ]; then
+          echo "INSTALL_DIR=$(echo ${HOME}/biodynamo-*)" >> $GITHUB_ENV
+        fi
 
-#     # - name: Cache Third Party Packages
-#     #   uses: actions/cache@v2
-#     #   with:
-#     #     path: build/third_party
-#     #     key: ${{ runner.os }}-third-party-${{ hashFiles('cmake/external/SHA256Digests.cmake') }}
+    # - name: Cache Third Party Packages
+    #   uses: actions/cache@v2
+    #   with:
+    #     path: build/third_party
+    #     key: ${{ runner.os }}-third-party-${{ hashFiles('cmake/external/SHA256Digests.cmake') }}
 
-#     - name: Build BioDynaMo
-#       shell: zsh {0}
-#       run: |
-#         cmake \
-#           -Dopencl=OFF \
-#           -Dparaview=ON \
-#           -Dbenchmark=ON \
-#           -Dlibgit2=ON \
-#           -DCMAKE_BUILD_TYPE=Release \
-#           -B build
-#         cmake --build build --parallel --config Release
+    - name: Build BioDynaMo
+      shell: zsh {0}
+      run: |
+        cmake \
+          -Dopencl=OFF \
+          -Dparaview=ON \
+          -Dbenchmark=ON \
+          -Dlibgit2=ON \
+          -DCMAKE_BUILD_TYPE=Release \
+          -B build
+        cmake --build build --parallel --config Release
 
-#     # Don't do this in the `Build BioDynaMo step`, because notebooks might time out in GHA
-#     # runners, while waiting for other targets to be compiled. Run notebooks only on 
-#     # macOS 10.15 until we managed to compile ROOT for 11.6 again.
-#     - name: Run notebooks
-#       shell: zsh {0}
-#       run: |
-#         cmake \
-#           -Dnotebooks=ON \
-#           -B build
-#         cmake --build build --parallel --config Release --target notebooks  -- -j1
-#       if: matrix.os == 'macos-10.15'
+    # Don't do this in the `Build BioDynaMo step`, because notebooks might time out in GHA
+    # runners, while waiting for other targets to be compiled. Run notebooks only on 
+    # macOS 10.15 until we managed to compile ROOT for 11.6 again.
+    - name: Run notebooks
+      shell: zsh {0}
+      run: |
+        cmake \
+          -Dnotebooks=ON \
+          -B build
+        cmake --build build --parallel --config Release --target notebooks  -- -j1
+      if: matrix.os == 'macos-10.15'
 
-#     - name: System tests BioDynaMo
-#       shell: zsh {0}
-#       working-directory: build
-#       run: |
-#         source $(find /Users -path "*/bin/*" -name "*thisbdm.sh")
-#         root --version
-#         root -config
-#         git config --system user.name "Test User"
-#         git config --system user.email user@test.com
-#         make run-demos
+    - name: System tests BioDynaMo
+      shell: zsh {0}
+      working-directory: build
+      run: |
+        source $(find /Users -path "*/bin/*" -name "*thisbdm.sh")
+        root --version
+        root -config
+        git config --system user.name "Test User"
+        git config --system user.email user@test.com
+        make run-demos
 
-#     - name: Notify Slack
-#       uses: 8398a7/action-slack@v3
-#       with:
-#         status: custom
-#         fields: workflow,job,commit,repo,ref,author,took,message
-#         custom_payload: |
-#           {
-#             username: 'GitHub CI',
-#             icon_emoji: ':octocat:',
-#             attachments: [{
-#               color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
-#               text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}\n${process.env.AS_MESSAGE}`
-#             }]
-#           }
-#       env:
-#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-#         MATRIX_CONTEXT: ${{ toJson(matrix) }} # Required when using matrix
-#       # Notify Slack step should run when the following holds true:
-#       #   * One of the previous steps 1) succeeded, 2) failed, or 3) was cancelled
-#       #   * This workflow is triggered from our base repository (i.e. forked PRs don't
-#       #     have the right to push Slack message to our channel)
-#       if: ${{ ( failure() || success() || cancelled() ) && ( github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name ) }}
+    - name: Notify Slack
+      uses: 8398a7/action-slack@v3
+      with:
+        status: custom
+        fields: workflow,job,commit,repo,ref,author,took,message
+        custom_payload: |
+          {
+            username: 'GitHub CI',
+            icon_emoji: ':octocat:',
+            attachments: [{
+              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
+              text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}\n${process.env.AS_MESSAGE}`
+            }]
+          }
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+        MATRIX_CONTEXT: ${{ toJson(matrix) }} # Required when using matrix
+      # Notify Slack step should run when the following holds true:
+      #   * One of the previous steps 1) succeeded, 2) failed, or 3) was cancelled
+      #   * This workflow is triggered from our base repository (i.e. forked PRs don't
+      #     have the right to push Slack message to our channel)
+      if: ${{ ( failure() || success() || cancelled() ) && ( github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name ) }}
